# Generated by Django 3.2.9 on 2021-11-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'percentage'), ('amount', 'amount')], default='percentage', max_length=10)),
                ('discount', models.FloatField(default=0)),
                ('paid_status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('partial', 'partial')], default='paid', max_length=15)),
                ('total', models.FloatField()),
                ('due_amount', models.FloatField(default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_manager_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, null=True)),
                ('price', models.FloatField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_manager_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_manager_app.product')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_manager_app.tax')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_manager_app.order')),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_manager_app.paymentmode')),
            ],
        ),
    ]
