# Generated by Django 3.2.9 on 2021-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager_app', '0002_auto_20211107_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
