# Generated by Django 3.2.5 on 2021-12-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager_app', '0003_alter_paymentmode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoice_manager_app.order'),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='invoice_manager_app.paymentmode'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='invoice_manager_app.order'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='invoice_manager_app.product'),
        ),
    ]
